config/routes.rb
Rails.application.routes.draw do
	 resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get '/home' => 'home#home'
  get '/home/map' => 'home#map'
  get '/game' => 'game#game'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/game_controller.rb
class GameController < ApplicationController
end
def game
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end
def home
end
def map
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/index.html.erb
<%provide(:title , 'Comments') %>
<html id='homebackground'>
<link type="text/css" rel="stylesheet" href="homebackground.css" />
<ul class='hnav'>
  <li><a href="/home">Home</a></li>
  <li><a class='active' href="/home/comments">Comments</a></li>
  <li class="dropdown">
    <a href="#" class="dropbtn">Social Media</a>
    <div class="dropdown-content">
      <a href="https://www.facebook.com/profile.php?id=100008308512312">Facebook</a>
      <a href="https://www.instagram.com/justin_sungg/">Instagram</a>
    </div>
  </li>
</ul>

<br>
<br>
<br>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

>>>>>>> 919d1c5b2896eeaa1da80fdb2c07246e3bd49263

app/views/articles/new.html.erb
<<<<<<< HEAD
<h1> New Article </h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
=======
<h1> Hi </h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
>>>>>>> js

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/game/game.html.erb
<%provide(:title, 'Game Page') %>
<html id='gamebackground'> <!--Remember if we create a game background then create gamebackground.css-->

<head>
	<link type="text/css" rel="stylesheet" href="game.css" />
	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css"> <!-- Just for the general font and progress bar-->
<body>
	<title>Ecowars</title>
</head>
<!-- Game menu bar -->
<span style="font-size:30px;cursor:pointer" onclick="gopenNav()">&#9776; Game Menu</span>
<div id="gSidenav" class="gsidenav">
  <p href="javascript:void(0)" class="gclosebtn" onclick="gcloseNav()">&times;</a>
  <p id = "plants" onclick="gexpand()">Plants</p>
  <div class="sub-menu" id = "sub-menu-plants">
		 <div class="buynsell"><p>Trees</p></div>
		 <div class="buynsell"><p>Forests</p>
         	<ul>
            	<li><p onclick ="buyforests()">Buy</p></li>
            	<li><p onclick ="sellforests()">Sell</p></li>
            </ul>
         </div>
         <div class="buynsell"><p>Sub Item 3</p></div>
         <div class="buynsell"><p>Sub Item 4</p></div>

  </div>
  <p id = "protection" onclick="gexpand()">Protection</p>
  <div class="sub-menu" id = "sub-menu-protection">
         <div class="buynsell"><p>Sub Item 1</p></div>
         <div class="buynsell"><p>Sub Item 2</p></div>
         <div class="buynsell"><p>Sub Item 3</p></div>
         <div class="buynsell"><p>Sub Item 4</p></div>
  </div>
  <p id = "upgrades" onclick="gexpand()">Upgrades</p>
  <div class="sub-menu" id = "sub-menu-upgrades">
         <div class="buynsell"><p>Sub Item 1</p></div>
         <div class="buynsell"><p>Sub Item 2</p></div>
         <div class="buynsell"><p>Sub Item 3</p></div>
         <div class="buynsell"><p>Sub Item 4</p></div>
  </div>
  <p id = "gamemenu" onclick="gexpand()">Game Menu</p>
  <div class="sub-menu" id = "sub-menu-gamemenu">
         <div class="buynsell"><p>Sub Item 1</p></div>
         <div class="buynsell"><p>Sub Item 2</p></div>
         <div class="buynsell"><p>Sub Item 3</p></div>
         <div class="buynsell"><p>Sub Item 4</p></div>
  </div>
</div>

<!-- Use the element to open the sidenav -->

<!--Copied the javscript into html because javascript in the js file doesnt work other than jquery-->

<script>
/* Set the width of the side navigation to 250px and the left margin of the page content to 250px */
function gopenNav() {
    document.getElementById("gSidenav").style.width = "230px";
    document.getElementById("gmain").style.marginLeft = "230px";
}

function gexpand() {
	document.getElementbyId("gSidenav").style.width = "400px";
	document.getElementById("gmain").style.marginLeft = "400px";

}
/* Set the width of the side navigation to 0 and the left margin of the page content to 0 */
function gcloseNav() {
    document.getElementById("gSidenav").style.width = "0";
    document.getElementById("gmain").style.marginLeft = "0";
}


</script>

<!-- Everything must be put inside the div gmain -->

<div id="gmain">
	<div id = "intro">
		<h1>SAVE THE WORLD!</h1>
		<p>Buy <strong>TREES</strong> to save the world from human destruction!</p>
	</div>


  	<div id="meter"><div id="progress"><div id="demo" class="w3-container w3-text-white">0%</div></div> </div>


<script>
// /*Progress bar, for some odd reason it wont work in JS so we put it here //
var barcounter = setInterval(bar, 1000);

var percent= 0; 
var resourcecount = 0;
var progress = document.getElementById("progress"); 
function bar(){ 
  percent = (resourcecount/10000)*100;
  if(percent>=100) {
    percent = 100;
    progress.style.width = percent + "%";
    percent = Math.round(percent); //makes the progress round to whole numbers
    document.getElementById("demo").innerHTML = percent * 1  + '%';
  }
  else {
    progress.style.width = percent + "%";
    percent = Math.round(percent); //makes the progress round to whole number
    document.getElementById("demo").innerHTML = percent * 1  + '%';
  };     
} 
</script>

	<div id = "Main">
		<div class="box">
			<p>Trees</p>
        	<p id="treeqtydisplay">0</p>
        	<p>Forests</p>
        	<p id="forestqtydisplay">0</p>
    	</div>

		<div id = "buy">
			<input type = "button" value = "Add by one"  onclick ="buytrees()">
			
		</div>

		<div id = "sell">
			<input type = "button" value = "Sell by one"  onclick="selltrees()">
	
			</button>
		</div>
	</div>

	<div>
	<p id ="timer">Timer</p>
	<p id="resources"></p>
	</div>

	<div>
	<p> Waves n stuff! </p>
	<p id = "waves"></p>
	</div>
</div>

app/views/home/game.html.erb
<%provide(:title, 'Game Page') %>

<head>
	<link type="text/css" rel="stylesheet" href="game.css" />
	<title>Ecowars</title>
</head>

<body>
	<div class= "nature">
		
	</div>
	<div id= "humans">
		
	</div>
	<div id= "border">

	</div>
	<div id= "game_menu">

	</div>
	<div id= "clicker">
	<img src = http://www.clker.com/cliparts/t/f/p/b/l/o/small-pointy-pine-tree-hi.png>
	</div>
</body>

app/views/home/home.html.erb
<%provide(:title , 'Home page') %>
<html id='homebackground'>
<link type="text/css" rel="stylesheet" href="homebackground.css" />
<ul class='hnav'>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="#comments">Comments</a></li>
  <li class="dropdown">
    <a href="#" class="dropbtn">Social Media</a>
    <div class="dropdown-content">
      <a href="https://www.facebook.com/profile.php?id=100008308512312">Facebook</a>
      <a href="https://www.instagram.com/justin_sungg/">Instagram</a>
    </div>
  </li>
</ul>





<!-- Login/ User display interface after clicking play -->



<!--Development popup-->
<div class="popup">
    <div class="popupcontent">
        <h2>Thank you for joining this site.</h2>
        <p>This site is currently in beta stages and is unavailable to the public. Our developers are working on something fun and awesome - check back later for more!</p>

        <p>-Justin</p>
        <p class="xclose">x</p>
    </div>
</div>

<body>
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Dramatically Engage.</h1>
            <p>Take part in a game where humans are pitted against the retaliating spectrum of nature.</p>
            <p>Navigate to the top to begin.</p>
        </div>
         <button1 class="engagenow" onclick="document.getElementById('login').style.display='block'">ENGAGE NOW</button1>
    </div>
</header>



<div id="login" class="modal">
  
  <form class="modal-content animate">
    <div class="imgcontainer">
      <span onclick="document.getElementById('login').style.display='none'" class="close">&times;</span>
      <img src="http://dy-communication.com/wp-content/uploads/2015/10/user-avatar.png" class="avatar">
    </div>

    <div class="container">
      <label style='font-size:20px'><b>Username</b></label>      
      <input type="text" placeholder="Enter Username" id ="uname" required> <!--Declare variables for uname and pass and display it in game.html.erb-->
      
      <label style='font-size:20px'><b>Password</b></label>
      <input type="password" placeholder="Enter Password" id="psw" required>
       
        <a href="/home/map" id='loginbtn'>Login</a>
      <input type="checkbox" checked="checked"> Remember me
    </div>

    <div class="logincontainer">
      <button type="button" onclick="document.getElementById('login').style.display='none'" class="cancelbtn">Cancel</button>
      <span id='forgotpass'>Forgot password? Email jsung2000@gmail.com or xrocxion@gmail.com.</span>
    </div>
  </form>
</div>

</body>

</div>
</html>

app/views/home/map.html.erb
<%provide(:title, 'Map') %>
<html id='homebackground'>
<link type="text/css" rel="stylesheet" href="homebackground.css" />

<div id="hnav" class="hnav">
    <div class='hlinks'>
        <a href="#">Help</a>
        <a href="#">Contact</a>
        <a href="#">Social Media</a>
        <%= link_to 'Back', home_path %>
    </div>
</div>
<body>
	<div style='position:absolute;z-index:0;left:0;top:0;width:100%;height:100%'>
  	<img src='http://www.timvandevall.com/wp-content/uploads/Blank-Treasure-Map.png' style='margin:auto' alt='[]' />
	</div>
</body>
<a href= /game>
<div class='region'>
	Unlocked map!
</div>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoWars| <%=yield(:title) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>